steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']

# Deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=k8s-deployment.yaml
  - --image=gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA
  - --location=${_ZONE}
  - --cluster=${_CLUSTER}

substitutions:
  _ZONE: us-central1-a
  _CLUSTER: my-gke-cluster

images:
- 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA'
